#!/bin/bash

# ./week3-check-2

# Author:  Murray Saul
# Date:    January 15, 2020
# Modified By: Jason Carman
# Modified: September 8, 2024
#
# Purpose: Check that user correctly created the specified directory
#          structure. This shell script will exit if errors,
#          but will provide feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.

logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab2-check-1_output.txt

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

 if eval $1; then
    echo -e "\e[0;32mOK\e[m"
 else
    echo -e "\e[0;31mWARNING\e[m"
    echo
    echo $2
    echo
    exit 1
 fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

if [ $PWD != $HOME ]; then
 # Start checking lab
 echo -e "\033[1mERROR:\033[0m"
 echo
 echo "You are NOT located in your HOME directory."
 echo -e "(i.e. \033[1m$HOME\033[0m )"
 echo
 echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
 echo -e "and confirm that you are"
 echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
 echo "and re-run this checking script."
 echo
 echo

 exit 1
fi

# System information gathering
echo "COMP1030 Week 3 Check 2 Script" > $logfile


# Start checking lab 3
echo | tee -a $logfile
echo -e "CHECKING YOUR LAB 3 WORK FOR USERNAME: \033[1m${USER}\033[0m" | tee -a $logfile

# Start checking lab3-check1
echo
echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check command "ls" was copied to your home directory
echo -n "Checking command file \"ls\" was copyied to your home directory: " | tee -a $logfile
check "test -f $HOME/ls" "The file pathname \"$HOME/ls\" does NOT exist. Check if you properly copied this file to your
home directory. Properly copy the /bin/ls file to your home directory and re-run this checking script" | tee -a $logfile

# Check file "ls" was copied to the "tutorial3" directory
echo -n "Checking \"ls\" file was copied to your \"tutorial3\" directory: " | tee -a $logfile
check "test -f $HOME/tutorial3/ls" "The file pathname \"~/tutorial3/ls\" does NOT exist. Reissue the correct command to
copy the ls file from the \"/bin\" directory to \"../..\" pathname which is your \"tutorial3\" directory and re-run this
checking script" | tee -a $logfile

# Check file "ls.bk" moved to "commands" directory
echo -n "Checking \"ls.bk\" file was movied to the \"tutorial3/practice/commands\" directory: " | tee -a $logfile
check "test -f $HOME/tutorial3/practice/commands/ls.bk" "The file pathname \"$HOME/tutorial3/practice/commands/ls.bk\" d
oes NOT exist. Issue the correct command to move the ls.bak file in your \"examples\" directory to the \"commands\" dire
ctory using relative pathnames and re-run this checking script" | tee -a $logfile


# Check directory "notes" copied to "examples" directory
echo -n "Checking \"tutorial3/notes\" directory has been copied to the \"examples\" directory: " | tee -a $logfile
check "test -d $HOME/tutorial3/practice/examples/notes" "The directory pathname \"$HOME/tutorial3/practice/examples/note
s\" does NOT exist. Issue the correct command to copy the \"notes\" directory to the \"examples\" directory using relati
ve pathnames and re-run this checking script" | tee -a $logfile

# Check if "notes" directory moved to "commands" directory
echo -n "Checking \"tutorial3/notes\" directory has been moved to the \"tutorial3/practice/commands\" directory: " | tee
-a $logfile
check "test -d $HOME/tutorial3/practice/commands/notes" "The directory pathname \"$HOME/tutorial3/practice/commands/note
s\" does NOT exist. Re-issue the correct command and re-run this checking script" | tee -a $logfile


warningcount=$(grep -c "WARNING" $logfile)

echo | tee -a $logfile
echo | tee -a $logfile

if [ $warningcount == 0 ]; then
 echo "Congratulations!" | tee -a $logfile
 echo | tee -a $logfile
 echo "You have successfully completed Week 3 - Check 2." | tee -a $logfile
 echo
else
 echo "Your Lab is not complete." | tee -a $logfile
 echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi
