#!/bin/bash

# ./week5-check-1

# Author:  Murray Saul
# Date:    January 15, 2020
# Modified By: Jason Carman
# Modified: September 8, 2024
#
# Purpose: Check that user correctly created a series of text files.
#          This shell script will exit if errors,
#          but will provide feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.

logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab2-check-1_output.txt

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1; then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo
     echo $2
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

if [ $PWD != $HOME ]; then
  # Start checking lab
  echo -e "\033[1mERROR:\033[0m"
  echo
  echo "You are NOT located in your HOME directory."
  echo -e "(i.e. \033[1m$HOME\033[0m )"
  echo
  echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
  echo -e "and confirm that you are"
  echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
  echo "and re-run this checking script."
  echo
  echo

  exit 1
fi

# System information gathering
echo "COMP1030 Week 3 Check 3 Script" > $logfile


# Start checking lab 3
echo | tee -a $logfile
echo -e "CHECKING YOUR LAB 3 WORK FOR USERNAME: \033[1m${USER}\033[0m" | tee -a $logfile

# Start checking lab3-check1
echo
echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo


# Check that the "redirect" directory was created
echo -n "Checking that the \"redirect\" directory was created in home directory: " | tee -a $logfile
check "test -d $HOME/redirect" "The directory pathname \"$HOME/redirect\" does NOT exist. Create this directory and re-run this checking script" | tee -a $logfile
  





# Check that the text file "unsort.txt" was created in the "redirect" directory
echo -n "Checking text file \"unsort.txt\" was in the \"redirect\" directory: " | tee -a $logfile
check "test -f $HOME/redirect/unsort.txt" "The file pathname \"$HOME/redirect/unsort.txt\" does NOT exist. Re-issue the Linux pipe command to generate this file and re-run this checking script" | tee -a $logfile

# Check that the text file "sort.txt" was created in the "redirect" directory
echo -n "Checking text file \"sort.txt\" was in the \"redirect\" directory: " | tee -a $logfile
check "test -f $HOME/redirect/sort.txt" "The file pathname \"$HOME/redirect/sort.txt\" does NOT exist. Re-issue the Linux pipeline command to generate this file and re-run this checking script" | tee -a $logfile

# Check that the text file "match.txt" was created in the "redirect" directory
echo -n "Checking text file \"match.txt\" was in the \"redirect\" directory: " | tee -a $logfile
check "test -f $HOME/redirect/match.txt" "The file pathname \"$HOME/redirect/match.txt\" does NOT exist. Re-issue the Linux pipeline command to generate this file and re-run this checking script" | tee -a $logfile




warningcount=$(grep -c "WARNING" $logfile)

echo | tee -a $logfile
echo | tee -a $logfile

if [ $warningcount == 0 ]; then
  echo "Congratulations!" | tee -a $logfile
  echo | tee -a $logfile
  echo "You have successfully completed Week 3 - Check 3." | tee -a $logfile
  echo
else
  echo "Your Lab is not complete." | tee -a $logfile
  echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi
