#!/bin/bash

# ./week4-check-2

# Author:  Murray Saul
# Date:    January 15, 2020
# Modified By: Jason Carman
# Modified: September 8, 2024
#
# Purpose: Check that user correctly created a series of text files.
#          This shell script will exit if errors,
#          but will provide feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.

logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab2-check-1_output.txt

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1; then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo
     echo $2
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

if [ $PWD != $HOME ]; then
  # Start checking lab
  echo -e "\033[1mERROR:\033[0m"
  echo
  echo "You are NOT located in your HOME directory."
  echo -e "(i.e. \033[1m$HOME\033[0m )"
  echo
  echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
  echo -e "and confirm that you are"
  echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
  echo "and re-run this checking script."
  echo
  echo

  exit 1
fi

# System information gathering
echo "COMP1030 Week 3 Check 3 Script" > $logfile


# Start checking lab 4
echo | tee -a $logfile
echo -e "CHECKING YOUR LAB 4 WORK FOR USERNAME: \033[1m${USER}\033[0m" | tee -a $logfile

# Start checking week4-check-2
echo
echo -e "\033[1mCHECKING YOUR WORK:\033[0m"


# Check that the "redirect" directory exists 
echo -n "Checking that the \"redirect\" directory still exists in home directory: " | tee -a $logfile
check "test -d $HOME/redirect" "The directory pathname \"$HOME/redirect\" does NOT exist. Create this directory and re-run this checking script" | tee -a $logfile



# Check that the text file "cars" was created in the "redirect" directory
echo -n "Checking text file \"cars\" was in the \"redirect\" directory: " | tee -a $logfile
check "test -f $HOME/redirect/cars" "The file pathname \"$HOME/redirect/cars\" does NOT exist. Re-issue the Linux command to copy this text file from the github directory to your \"redirect\" directory and re-run this checking script" | tee -a $logfile




# Check that the text file "count.txt" was created in the "redirect" directory
echo -n "Checking text file \"count.txt\" was in the \"redirect\" directory: " | tee -a $logfile
check "test -f $HOME/redirect/count.txt" "The file pathname \"$HOME/redirect/output.txt\" does NOT exist. Re-issue the Linux command with redirection symbol to generate this file and re-run this checking script" | tee -a $logfile

# Check that the text file "count1.txt" was created in the "redirect" directory
echo -n "Checking text file \"count1.txt\" was in the \"redirect\" directory: " | tee -a $logfile
check "test -f $HOME/redirect/count1.txt" "The file pathname \"$HOME/redirect/count1.txt\" does NOT exist. Re-issue the Linux command with redirection symbol to generate this file and re-run this checking script" | tee -a $logfile

# Check that the text file "count2.txt" was created in the "redirect" directory
echo -n "Checking text file \"count2.txt\" was in the \"redirect\" directory: " | tee -a $logfile
check "test -f $HOME/redirect/count2.txt" "The file pathname \"$HOME/redirect/count2.txt\" does NOT exist. Re-issue the Linux command with redirection symbol to generate this file and re-run this checking script" | tee -a $logfile






# Check that the text file "field5.txt" was created in the "redirect" directory
echo -n "Checking text file \"field5.txt\" was in the \"redirect\" directory: " | tee -a $logfile
check "test -f $HOME/redirect/field5.txt" "The file pathname \"$HOME/redirect/field5.txt\" does NOT exist. Re-issue the Linux command with redirection symbol to generate this file and re-run this checking script" | tee -a $logfile

# Check that the text file "field123.txt" was created in the "redirect" directory
echo -n "Checking text file \"field123.txt\" was in the \"redirect\" directory: " | tee -a $logfile
check "test -f $HOME/redirect/field123.txt" "The file pathname \"$HOME/redirect/filed123.txt\" does NOT exist. Re-issue the Linux command with redirection symbol to generate this file and re-run this checking script" | tee -a $logfile

# Check that the text file "field15.txt" was created in the "redirect" directory
echo -n "Checking text file \"field15.txt\" was in the \"redirect\" directory: " | tee -a $logfile
check "test -f $HOME/redirect/field15.txt" "The file pathname \"$HOME/redirect/field15.txt\" does NOT exist. Re-issue the Linux command with redirection symbol to generate this file and re-run this checking script" | tee -a $logfile




# Check that the text file "listing.txt" was created in the "redirect" directory
echo -n "Checking text file \"listing.txt\" was in the \"redirect\" directory: " | tee -a $logfile
check "test -f $HOME/redirect/listing.txt" "The file pathname \"$HOME/redirect/listing.txt\" does NOT exist. Re-issue the Linux command with redirection symbol to generate this file and re-run this checking script" | tee -a $logfile

# Check that the text file "combined.txt" was created in the "redirect" directory
echo -n "Checking text file \"combined.txt\" was in the \"redirect\" directory: " | tee -a $logfile
check "test -f $HOME/redirect/combined.txt" "The file pathname \"$HOME/redirect/combined.txt\" does NOT exist. Re-issue the Linux command with redirection symbol to generate this file and re-run this checking script" | tee -a $logfile

# Check that the text file "myoutput.txt" was created in the "redirect" directory
echo -n "Checking text file \"myoutput.txt\" was in the \"redirect\" directory: " | tee -a $logfile
check "test -f $HOME/redirect/myoutput.txt" "The file pathname \"$HOME/redirect/myoutput.txt\" does NOT exist. Re-issue the Linux command with redirection symbol to generate this file and re-run this checking script" | tee -a $logfile

# Check that the text file "result.txt" was created in the "redirect" directory
echo -n "Checking text file \"result.txt\" was in the \"redirect\" directory: " | tee -a $logfile
check "test -f $HOME/redirect/result.txt" "The file pathname \"$HOME/redirect/result.txt\" does NOT exist. Re-issue the Linux command with redirection symbol to generate this file and re-run this checking script" | tee -a $logfile



warningcount=$(grep -c "WARNING" $logfile)

echo | tee -a $logfile

if [ $warningcount == 0 ]; then
  echo "Congratulations!" | tee -a $logfile
  echo "You have successfully completed Week 4 - Check 2." | tee -a $logfile
  echo
else
  echo "Your Lab is not complete." | tee -a $logfile
  echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi
