#!/bin/bash

# ./week8-check-3

# Author:  Murray Saul
# Date:    January 15, 2020
# Modified By: Jason Carman
# Modified: September 8, 2024
#
# Purpose: Check that sysadmin created and removed the correct users

logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab2-check-1_output.txt

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1; then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo
     echo $2
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

if [ $PWD != $HOME ]; then
  # Start checking lab
  echo -e "\033[1mERROR:\033[0m"
  echo
  echo "You are NOT located in your HOME directory."
  echo -e "(i.e. \033[1m$HOME\033[0m )"
  echo
  echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
  echo -e "and confirm that you are"
  echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
  echo "and re-run this checking script."
  echo
  echo

  exit 1
fi

# System information gathering
echo "COMP1030 Week 8 Check 3 Script" > $logfile


# Start checking lab 6
echo | tee -a $logfile
echo -e "CHECKING YOUR LAB 6 WORK FOR USERNAME: \033[1m${USER}\033[0m" | tee -a $logfile

# Start checking week8-check-3
echo
echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo


# Check that  "welcome" group was created in /etc/group
echo -n "Checking that the \"welcome\" group created in /etc/group: " | tee -a $logfile
check "grep welcome /etc/group > /dev/null 2> /dev/null" "The group \"welcome\" does not exist. check for spelling and lowercase (you can use the groupdel command to remove a group and then re-add the proper group name). Once corrected, re-run this checking script" | tee -a $logfile

# Check that that the your original username is added to "welcome group"
echo -n "Checking your original username \"$USER\" is added to \"welcome\" group: " | tee -a $logfile
check "grep welcome /etc/group | grep $USER > /dev/null 2> /dev/null" "Your username ($USER) has not been added to the \"welcome\" group. Issue the usermod command to add your username to the welcome group. When fixed,  re-run this checking script" | tee -a $logfile

# Check that that username "user2" is added to "welcome group"
echo -n "Checking that username \"user2\" is added to \"welcome\" group: " | tee -a $logfile
check "grep welcome /etc/group | grep user2 > /dev/null 2> /dev/null" "Your the username \"user2\" has not been added to the \"welcome\" group. Issue the usermod command to add that username to the welcome group. When fixed,  re-run this checking script" | tee -a $logfile






warningcount=$(grep -c "WARNING" $logfile)

echo | tee -a $logfile
echo | tee -a $logfile

if [ $warningcount == 0 ]; then
  echo "Congratulations!" | tee -a $logfile
  echo | tee -a $logfile
  echo "You have successfully completed Week 8 - Check 3." | tee -a $logfile
  echo
else
  echo "Your Lab is not complete." | tee -a $logfile
  echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi
